/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_OSXApplication */

#ifndef _Included_ch_randelshofer_quaqua_osx_OSXApplication
#define _Included_ch_randelshofer_quaqua_osx_OSXApplication
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_randelshofer_quaqua_osx_OSXApplication_DEBUG
#define ch_randelshofer_quaqua_osx_OSXApplication_DEBUG 1L
/* Inaccessible static: isNativeCodeAvailable */
#undef ch_randelshofer_quaqua_osx_OSXApplication_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_osx_OSXApplication_EXPECTED_NATIVE_CODE_VERSION 2L
/* Inaccessible static: ICON_IMAGE_LOCK */
/*
 * Class:     ch_randelshofer_quaqua_osx_OSXApplication
 * Method:    nativeRequestUserAttention
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_OSXApplication_nativeRequestUserAttention
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXApplication
 * Method:    nativeGetIconImage
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_osx_OSXApplication_nativeGetIconImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXApplication
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXApplication_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
