/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_OSXFile */

#ifndef _Included_ch_randelshofer_quaqua_osx_OSXFile
#define _Included_ch_randelshofer_quaqua_osx_OSXFile
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_ALIAS
#define ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_ALIAS 2L
#undef ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_DIRECTORY
#define ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_DIRECTORY 1L
#undef ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_FILE
#define ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_FILE 0L
#undef ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_UNKOWN
#define ch_randelshofer_quaqua_osx_OSXFile_FILE_TYPE_UNKOWN -1L
#undef ch_randelshofer_quaqua_osx_OSXFile_EXPECTED_NATIVE_CODE_VERSION
#define ch_randelshofer_quaqua_osx_OSXFile_EXPECTED_NATIVE_CODE_VERSION 5L
/* Inaccessible static: labelColors */
/* Inaccessible static: isNativeCodeAvailable */
/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetFileType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetFileType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeResolveAlias
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeResolveAlias__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeResolveAliasType
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeResolveAliasType__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeToSerializedAlias
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeToSerializedAlias
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeResolveAlias
 * Signature: ([BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeResolveAlias___3BZ
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeResolveAliasType
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeResolveAliasType___3BZ
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetLabel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetLabel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetKindString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetKindString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetIconImage
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetIconImage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetQuickLookThumbnailImage
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetQuickLookThumbnailImage
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetBasicItemInfoFlags
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetBasicItemInfoFlags
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetDisplayName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetDisplayName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_randelshofer_quaqua_osx_OSXFile
 * Method:    nativeGetNativeCodeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_randelshofer_quaqua_osx_OSXFile_nativeGetNativeCodeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
